# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ActivityBreedModuleMsg.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import TaskModuleMsg_pb2 as TaskModuleMsg__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ActivityBreedModuleMsg.proto',
  package='com.common.msg',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1c\x41\x63tivityBreedModuleMsg.proto\x12\x0e\x63om.common.msg\x1a\x13TaskModuleMsg.proto\".\n\x18\x41\x63tivityBreedInfoRequest\x12\x12\n\nactivityId\x18\x01 \x02(\t\"V\n\tBreedTask\x12\r\n\x05state\x18\x01 \x02(\x05\x12*\n\x06params\x18\x02 \x03(\x0b\x32\x1a.com.common.msg.ProtoTypes\x12\x0e\n\x06taskId\x18\x03 \x02(\t\"p\n\x19\x41\x63tivityBreedInfoResponse\x12-\n\nbreedTasks\x18\x01 \x03(\x0b\x32\x19.com.common.msg.BreedTask\x12\x12\n\nbreedCount\x18\x02 \x01(\x05\x12\x10\n\x08progress\x18\x03 \x01(\x05\":\n\x14TakeTaskAwardRequest\x12\x12\n\nactivityId\x18\x01 \x02(\t\x12\x0e\n\x06taskId\x18\x02 \x02(\t\"\x17\n\x15TakeTaskAwardResponse\"=\n\x15UnlockProgressRequest\x12\x12\n\nactivityId\x18\x01 \x02(\t\x12\x10\n\x08progress\x18\x02 \x02(\x05\"\x18\n\x16UnlockProgressResponse*\xb7\x01\n ActivityBreedModuleMsgSubCommand\x12\x32\n,ACTIVITYBREEDMODULEMSG_SUB_ACTIVITYBREEDINFO\x10\xf5\xcb\x01\x12.\n(ACTIVITYBREEDMODULEMSG_SUB_TAKETASKAWARD\x10\xf6\xcb\x01\x12/\n)ACTIVITYBREEDMODULEMSG_SUB_UNLOCKPROGRESS\x10\xf7\xcb\x01'
  ,
  dependencies=[TaskModuleMsg__pb2.DESCRIPTOR,])

_ACTIVITYBREEDMODULEMSGSUBCOMMAND = _descriptor.EnumDescriptor(
  name='ActivityBreedModuleMsgSubCommand',
  full_name='com.common.msg.ActivityBreedModuleMsgSubCommand',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACTIVITYBREEDMODULEMSG_SUB_ACTIVITYBREEDINFO', index=0, number=26101,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ACTIVITYBREEDMODULEMSG_SUB_TAKETASKAWARD', index=1, number=26102,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ACTIVITYBREEDMODULEMSG_SUB_UNLOCKPROGRESS', index=2, number=26103,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=494,
  serialized_end=677,
)
_sym_db.RegisterEnumDescriptor(_ACTIVITYBREEDMODULEMSGSUBCOMMAND)

ActivityBreedModuleMsgSubCommand = enum_type_wrapper.EnumTypeWrapper(_ACTIVITYBREEDMODULEMSGSUBCOMMAND)
ACTIVITYBREEDMODULEMSG_SUB_ACTIVITYBREEDINFO = 26101
ACTIVITYBREEDMODULEMSG_SUB_TAKETASKAWARD = 26102
ACTIVITYBREEDMODULEMSG_SUB_UNLOCKPROGRESS = 26103



_ACTIVITYBREEDINFOREQUEST = _descriptor.Descriptor(
  name='ActivityBreedInfoRequest',
  full_name='com.common.msg.ActivityBreedInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='activityId', full_name='com.common.msg.ActivityBreedInfoRequest.activityId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=115,
)


_BREEDTASK = _descriptor.Descriptor(
  name='BreedTask',
  full_name='com.common.msg.BreedTask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='com.common.msg.BreedTask.state', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='com.common.msg.BreedTask.params', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='taskId', full_name='com.common.msg.BreedTask.taskId', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=203,
)


_ACTIVITYBREEDINFORESPONSE = _descriptor.Descriptor(
  name='ActivityBreedInfoResponse',
  full_name='com.common.msg.ActivityBreedInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='breedTasks', full_name='com.common.msg.ActivityBreedInfoResponse.breedTasks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='breedCount', full_name='com.common.msg.ActivityBreedInfoResponse.breedCount', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='progress', full_name='com.common.msg.ActivityBreedInfoResponse.progress', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=317,
)


_TAKETASKAWARDREQUEST = _descriptor.Descriptor(
  name='TakeTaskAwardRequest',
  full_name='com.common.msg.TakeTaskAwardRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='activityId', full_name='com.common.msg.TakeTaskAwardRequest.activityId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='taskId', full_name='com.common.msg.TakeTaskAwardRequest.taskId', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=319,
  serialized_end=377,
)


_TAKETASKAWARDRESPONSE = _descriptor.Descriptor(
  name='TakeTaskAwardResponse',
  full_name='com.common.msg.TakeTaskAwardResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=379,
  serialized_end=402,
)


_UNLOCKPROGRESSREQUEST = _descriptor.Descriptor(
  name='UnlockProgressRequest',
  full_name='com.common.msg.UnlockProgressRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='activityId', full_name='com.common.msg.UnlockProgressRequest.activityId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='progress', full_name='com.common.msg.UnlockProgressRequest.progress', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=404,
  serialized_end=465,
)


_UNLOCKPROGRESSRESPONSE = _descriptor.Descriptor(
  name='UnlockProgressResponse',
  full_name='com.common.msg.UnlockProgressResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=467,
  serialized_end=491,
)

_BREEDTASK.fields_by_name['params'].message_type = TaskModuleMsg__pb2._PROTOTYPES
_ACTIVITYBREEDINFORESPONSE.fields_by_name['breedTasks'].message_type = _BREEDTASK
DESCRIPTOR.message_types_by_name['ActivityBreedInfoRequest'] = _ACTIVITYBREEDINFOREQUEST
DESCRIPTOR.message_types_by_name['BreedTask'] = _BREEDTASK
DESCRIPTOR.message_types_by_name['ActivityBreedInfoResponse'] = _ACTIVITYBREEDINFORESPONSE
DESCRIPTOR.message_types_by_name['TakeTaskAwardRequest'] = _TAKETASKAWARDREQUEST
DESCRIPTOR.message_types_by_name['TakeTaskAwardResponse'] = _TAKETASKAWARDRESPONSE
DESCRIPTOR.message_types_by_name['UnlockProgressRequest'] = _UNLOCKPROGRESSREQUEST
DESCRIPTOR.message_types_by_name['UnlockProgressResponse'] = _UNLOCKPROGRESSRESPONSE
DESCRIPTOR.enum_types_by_name['ActivityBreedModuleMsgSubCommand'] = _ACTIVITYBREEDMODULEMSGSUBCOMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ActivityBreedInfoRequest = _reflection.GeneratedProtocolMessageType('ActivityBreedInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _ACTIVITYBREEDINFOREQUEST,
  '__module__' : 'ActivityBreedModuleMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.common.msg.ActivityBreedInfoRequest)
  })
_sym_db.RegisterMessage(ActivityBreedInfoRequest)

BreedTask = _reflection.GeneratedProtocolMessageType('BreedTask', (_message.Message,), {
  'DESCRIPTOR' : _BREEDTASK,
  '__module__' : 'ActivityBreedModuleMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.common.msg.BreedTask)
  })
_sym_db.RegisterMessage(BreedTask)

ActivityBreedInfoResponse = _reflection.GeneratedProtocolMessageType('ActivityBreedInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _ACTIVITYBREEDINFORESPONSE,
  '__module__' : 'ActivityBreedModuleMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.common.msg.ActivityBreedInfoResponse)
  })
_sym_db.RegisterMessage(ActivityBreedInfoResponse)

TakeTaskAwardRequest = _reflection.GeneratedProtocolMessageType('TakeTaskAwardRequest', (_message.Message,), {
  'DESCRIPTOR' : _TAKETASKAWARDREQUEST,
  '__module__' : 'ActivityBreedModuleMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.common.msg.TakeTaskAwardRequest)
  })
_sym_db.RegisterMessage(TakeTaskAwardRequest)

TakeTaskAwardResponse = _reflection.GeneratedProtocolMessageType('TakeTaskAwardResponse', (_message.Message,), {
  'DESCRIPTOR' : _TAKETASKAWARDRESPONSE,
  '__module__' : 'ActivityBreedModuleMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.common.msg.TakeTaskAwardResponse)
  })
_sym_db.RegisterMessage(TakeTaskAwardResponse)

UnlockProgressRequest = _reflection.GeneratedProtocolMessageType('UnlockProgressRequest', (_message.Message,), {
  'DESCRIPTOR' : _UNLOCKPROGRESSREQUEST,
  '__module__' : 'ActivityBreedModuleMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.common.msg.UnlockProgressRequest)
  })
_sym_db.RegisterMessage(UnlockProgressRequest)

UnlockProgressResponse = _reflection.GeneratedProtocolMessageType('UnlockProgressResponse', (_message.Message,), {
  'DESCRIPTOR' : _UNLOCKPROGRESSRESPONSE,
  '__module__' : 'ActivityBreedModuleMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.common.msg.UnlockProgressResponse)
  })
_sym_db.RegisterMessage(UnlockProgressResponse)


# @@protoc_insertion_point(module_scope)
