# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BuildingActivityModuleMsg.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ItemModuleMsg_pb2 as ItemModuleMsg__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='BuildingActivityModuleMsg.proto',
  package='com.common.msg',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1f\x42uildingActivityModuleMsg.proto\x12\x0e\x63om.common.msg\x1a\x13ItemModuleMsg.proto\"\x1d\n\x1b\x42uildingActivityInfoRequest\"L\n\x1c\x42uildingActivityInfoResponse\x12\x16\n\x0e\x66irstStartTime\x18\x01 \x02(\x03\x12\x14\n\x0c\x63urStartTime\x18\x02 \x02(\x03*^\n#BuildingActivityModuleMsgSubCommand\x12\x37\n2BUILDINGACTIVITYMODULEMSG_SUB_BUILDINGACTIVITYINFO\x10\xc5^'
  ,
  dependencies=[ItemModuleMsg__pb2.DESCRIPTOR,])

_BUILDINGACTIVITYMODULEMSGSUBCOMMAND = _descriptor.EnumDescriptor(
  name='BuildingActivityModuleMsgSubCommand',
  full_name='com.common.msg.BuildingActivityModuleMsgSubCommand',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BUILDINGACTIVITYMODULEMSG_SUB_BUILDINGACTIVITYINFO', index=0, number=12101,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=181,
  serialized_end=275,
)
_sym_db.RegisterEnumDescriptor(_BUILDINGACTIVITYMODULEMSGSUBCOMMAND)

BuildingActivityModuleMsgSubCommand = enum_type_wrapper.EnumTypeWrapper(_BUILDINGACTIVITYMODULEMSGSUBCOMMAND)
BUILDINGACTIVITYMODULEMSG_SUB_BUILDINGACTIVITYINFO = 12101



_BUILDINGACTIVITYINFOREQUEST = _descriptor.Descriptor(
  name='BuildingActivityInfoRequest',
  full_name='com.common.msg.BuildingActivityInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=101,
)


_BUILDINGACTIVITYINFORESPONSE = _descriptor.Descriptor(
  name='BuildingActivityInfoResponse',
  full_name='com.common.msg.BuildingActivityInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='firstStartTime', full_name='com.common.msg.BuildingActivityInfoResponse.firstStartTime', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='curStartTime', full_name='com.common.msg.BuildingActivityInfoResponse.curStartTime', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=179,
)

DESCRIPTOR.message_types_by_name['BuildingActivityInfoRequest'] = _BUILDINGACTIVITYINFOREQUEST
DESCRIPTOR.message_types_by_name['BuildingActivityInfoResponse'] = _BUILDINGACTIVITYINFORESPONSE
DESCRIPTOR.enum_types_by_name['BuildingActivityModuleMsgSubCommand'] = _BUILDINGACTIVITYMODULEMSGSUBCOMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BuildingActivityInfoRequest = _reflection.GeneratedProtocolMessageType('BuildingActivityInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _BUILDINGACTIVITYINFOREQUEST,
  '__module__' : 'BuildingActivityModuleMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.common.msg.BuildingActivityInfoRequest)
  })
_sym_db.RegisterMessage(BuildingActivityInfoRequest)

BuildingActivityInfoResponse = _reflection.GeneratedProtocolMessageType('BuildingActivityInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _BUILDINGACTIVITYINFORESPONSE,
  '__module__' : 'BuildingActivityModuleMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.common.msg.BuildingActivityInfoResponse)
  })
_sym_db.RegisterMessage(BuildingActivityInfoResponse)


# @@protoc_insertion_point(module_scope)
