protoc -I=d:\pyprogram\PyTestTools\senditems\dragon\proto --python_out=d:\pyprogram\PyTestTools\senditems\dragon\proto d:\pyprogram\PyTestTools\senditems\dragon\proto\ActivityGiftModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\senditems\dragon\proto --python_out=d:\pyprogram\PyTestTools\senditems\dragon\proto d:\pyprogram\PyTestTools\senditems\dragon\proto\ActivityModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\senditems\dragon\proto --python_out=d:\pyprogram\PyTestTools\senditems\dragon\proto d:\pyprogram\PyTestTools\senditems\dragon\proto\AdsModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\senditems\dragon\proto --python_out=d:\pyprogram\PyTestTools\senditems\dragon\proto d:\pyprogram\PyTestTools\senditems\dragon\proto\BoxModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\senditems\dragon\proto --python_out=d:\pyprogram\PyTestTools\senditems\dragon\proto d:\pyprogram\PyTestTools\senditems\dragon\proto\BuffModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\senditems\dragon\proto --python_out=d:\pyprogram\PyTestTools\senditems\dragon\proto d:\pyprogram\PyTestTools\senditems\dragon\proto\BuildingActivityModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\senditems\dragon\proto --python_out=d:\pyprogram\PyTestTools\senditems\dragon\proto d:\pyprogram\PyTestTools\senditems\dragon\proto\BuildingModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\senditems\dragon\proto --python_out=d:\pyprogram\PyTestTools\senditems\dragon\proto d:\pyprogram\PyTestTools\senditems\dragon\proto\BuildingStealModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\senditems\dragon\proto --python_out=d:\pyprogram\PyTestTools\senditems\dragon\proto d:\pyprogram\PyTestTools\senditems\dragon\proto\ConvertFactoryModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\senditems\dragon\proto --python_out=d:\pyprogram\PyTestTools\senditems\dragon\proto d:\pyprogram\PyTestTools\senditems\dragon\proto\CoreModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\senditems\dragon\proto --python_out=d:\pyprogram\PyTestTools\senditems\dragon\proto d:\pyprogram\PyTestTools\senditems\dragon\proto\DayRewardModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\senditems\dragon\proto --python_out=d:\pyprogram\PyTestTools\senditems\dragon\proto d:\pyprogram\PyTestTools\senditems\dragon\proto\ErrorCodeEnums.proto
protoc -I=d:\pyprogram\PyTestTools\senditems\dragon\proto --python_out=d:\pyprogram\PyTestTools\senditems\dragon\proto d:\pyprogram\PyTestTools\senditems\dragon\proto\FactoryModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\senditems\dragon\proto --python_out=d:\pyprogram\PyTestTools\senditems\dragon\proto d:\pyprogram\PyTestTools\senditems\dragon\proto\FarmlandModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\senditems\dragon\proto --python_out=d:\pyprogram\PyTestTools\senditems\dragon\proto d:\pyprogram\PyTestTools\senditems\dragon\proto\FloatObjectModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\senditems\dragon\proto --python_out=d:\pyprogram\PyTestTools\senditems\dragon\proto d:\pyprogram\PyTestTools\senditems\dragon\proto\FriendsModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\senditems\dragon\proto --python_out=d:\pyprogram\PyTestTools\senditems\dragon\proto d:\pyprogram\PyTestTools\senditems\dragon\proto\GashaponModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\senditems\dragon\proto --python_out=d:\pyprogram\PyTestTools\senditems\dragon\proto d:\pyprogram\PyTestTools\senditems\dragon\proto\GatewayModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\senditems\dragon\proto --python_out=d:\pyprogram\PyTestTools\senditems\dragon\proto d:\pyprogram\PyTestTools\senditems\dragon\proto\GiftBoxModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\senditems\dragon\proto --python_out=d:\pyprogram\PyTestTools\senditems\dragon\proto d:\pyprogram\PyTestTools\senditems\dragon\proto\GMModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\senditems\dragon\proto --python_out=d:\pyprogram\PyTestTools\senditems\dragon\proto d:\pyprogram\PyTestTools\senditems\dragon\proto\ItemModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\senditems\dragon\proto --python_out=d:\pyprogram\PyTestTools\senditems\dragon\proto d:\pyprogram\PyTestTools\senditems\dragon\proto\LevelsModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\senditems\dragon\proto --python_out=d:\pyprogram\PyTestTools\senditems\dragon\proto d:\pyprogram\PyTestTools\senditems\dragon\proto\MagicalCreatureModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\senditems\dragon\proto --python_out=d:\pyprogram\PyTestTools\senditems\dragon\proto d:\pyprogram\PyTestTools\senditems\dragon\proto\MagicPassModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\senditems\dragon\proto --python_out=d:\pyprogram\PyTestTools\senditems\dragon\proto d:\pyprogram\PyTestTools\senditems\dragon\proto\MailModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\senditems\dragon\proto --python_out=d:\pyprogram\PyTestTools\senditems\dragon\proto d:\pyprogram\PyTestTools\senditems\dragon\proto\MonthSignInModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\senditems\dragon\proto --python_out=d:\pyprogram\PyTestTools\senditems\dragon\proto d:\pyprogram\PyTestTools\senditems\dragon\proto\OrderTaskModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\senditems\dragon\proto --python_out=d:\pyprogram\PyTestTools\senditems\dragon\proto d:\pyprogram\PyTestTools\senditems\dragon\proto\ProsperityModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\senditems\dragon\proto --python_out=d:\pyprogram\PyTestTools\senditems\dragon\proto d:\pyprogram\PyTestTools\senditems\dragon\proto\RandomShopModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\senditems\dragon\proto --python_out=d:\pyprogram\PyTestTools\senditems\dragon\proto d:\pyprogram\PyTestTools\senditems\dragon\proto\RichManModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\senditems\dragon\proto --python_out=d:\pyprogram\PyTestTools\senditems\dragon\proto d:\pyprogram\PyTestTools\senditems\dragon\proto\SceneModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\senditems\dragon\proto --python_out=d:\pyprogram\PyTestTools\senditems\dragon\proto d:\pyprogram\PyTestTools\senditems\dragon\proto\TaskModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\senditems\dragon\proto --python_out=d:\pyprogram\PyTestTools\senditems\dragon\proto d:\pyprogram\PyTestTools\senditems\dragon\proto\TeamBuildingModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\senditems\dragon\proto --python_out=d:\pyprogram\PyTestTools\senditems\dragon\proto d:\pyprogram\PyTestTools\senditems\dragon\proto\TeamModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\senditems\dragon\proto --python_out=d:\pyprogram\PyTestTools\senditems\dragon\proto d:\pyprogram\PyTestTools\senditems\dragon\proto\VipModuleMsg.proto
