protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\ActiveEggModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\ActivityBreedModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\ActivityDragonDrawModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\ActivityDragonExploitModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\ActivityDragonFishingModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\ActivityDragonSeasonModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\ActivityGiftModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\ActivityGoldPanningModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\ActivityLotteryModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\ActivityMapModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\ActivityModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\ActivityMonopolyModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\ActivityMowModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\ActivityParkourModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\ActivitySignInModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\ActivityThreeClearModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\AdsModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\AlchemyFurnaceModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\AnimalModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\BoxModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\BuffModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\ChatModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\CommonTaskModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\ConvertFactoryModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\CoreModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\CutVegetableModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\DayRewardModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\DiamondRebateModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\DiggingEventModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\DotTaskModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\DragonBindModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\DragonBubbleModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\DragonBuildingModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\DragonDrawModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\DragonMazeModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\ErrorCodeEnums.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\FactoryModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\FarmlandModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\FloatObjectModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\FriendsModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\GashaponModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\GatewayModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\GiftBoxModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\GiftModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\GlobalProgressModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\GMModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\GoldPassModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\GrowthFundModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\HangupModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\InviteFriendsModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\ItemModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\LevelMapModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\LevelsModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\LuckyCardModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\MagicalCreatureModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\MagicPassModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\MailModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\MiniGameModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\MiningModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\MonthSignInModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\OrderTaskModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\PiggyBankModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\PlayerStrategyModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\PlayGopherModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\ProsperityModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\RandomShopModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\RechargeModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\RecycleDragonModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\ReflowModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\RichManModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\RollGrassModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\ScarecrowModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\SceneModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\SevenDaysModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\SkinProduceModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\SmallBPModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\TaskModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\TeamMapModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\TeamModuleMsg.proto
protoc -I=e:\PyTools\dragon\proto --python_out=e:\PyTools\dragon\package e:\PyTools\dragon\proto\VipModuleMsg.proto
