protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\ActiveEggModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\ActivityBreedModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\ActivityDragonDrawModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\ActivityDragonExploitModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\ActivityGiftModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\ActivityMapModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\ActivityModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\ActivityParkourModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\AdsModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\AlchemyFurnaceModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\AnimalModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\BoxModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\BuffModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\ChatModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\CommonTaskModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\ConvertFactoryModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\CoreModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\DayRewardModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\DragonBubbleModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\DragonDrawModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\DragonMazeModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\ErrorCodeEnums.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\FactoryModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\FarmlandModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\FloatObjectModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\FriendsModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\GashaponModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\GatewayModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\GiftBoxModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\GiftModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\GMModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\GoldPassModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\GrowthFundModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\ItemModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\LevelsModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\MagicalCreatureModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\MagicPassModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\MailModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\MonthSignInModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\OrderTaskModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\PiggyBankModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\ProsperityModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\RandomShopModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\RechargeModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\RichManModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\ScarecrowModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\SceneModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\SkinProduceModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\TaskModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\TeamMapModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\TeamModuleMsg.proto
protoc -I=d:\pyprogram\PyTestTools\dragon\proto --python_out=d:\pyprogram\PyTestTools\dragon\proto d:\pyprogram\PyTestTools\dragon\proto\VipModuleMsg.proto
