# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ActivitySignInModuleMsg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x41\x63tivitySignInModuleMsg.proto\x12\x0e\x63om.common.msg\"*\n\x19\x41\x63tivitySignInInfoRequest\x12\r\n\x05\x61\x63tId\x18\x01 \x01(\t\"G\n\x1a\x41\x63tivitySignInInfoResponse\x12\x0c\n\x04\x64\x61ys\x18\x01 \x03(\x05\x12\x1b\n\x13supplementSignInCnt\x18\x02 \x01(\x05\"G\n\x15\x41\x63tivitySignInRequest\x12\r\n\x05\x61\x63tId\x18\x01 \x01(\t\x12\x0b\n\x03\x64\x61y\x18\x02 \x01(\x05\x12\x12\n\nsupplement\x18\x03 \x01(\x08\"\x18\n\x16\x41\x63tivitySignInResponse*\x8b\x01\n!ActivitySignInModuleMsgSubCommand\x12\x34\n.ACTIVITYSIGNINMODULEMSG_SUB_ACTIVITYSIGNININFO\x10\xad\xe8\x01\x12\x30\n*ACTIVITYSIGNINMODULEMSG_SUB_ACTIVITYSIGNIN\x10\xae\xe8\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ActivitySignInModuleMsg_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ACTIVITYSIGNINMODULEMSGSUBCOMMAND']._serialized_start=266
  _globals['_ACTIVITYSIGNINMODULEMSGSUBCOMMAND']._serialized_end=405
  _globals['_ACTIVITYSIGNININFOREQUEST']._serialized_start=49
  _globals['_ACTIVITYSIGNININFOREQUEST']._serialized_end=91
  _globals['_ACTIVITYSIGNININFORESPONSE']._serialized_start=93
  _globals['_ACTIVITYSIGNININFORESPONSE']._serialized_end=164
  _globals['_ACTIVITYSIGNINREQUEST']._serialized_start=166
  _globals['_ACTIVITYSIGNINREQUEST']._serialized_end=237
  _globals['_ACTIVITYSIGNINRESPONSE']._serialized_start=239
  _globals['_ACTIVITYSIGNINRESPONSE']._serialized_end=263
# @@protoc_insertion_point(module_scope)
