# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ActivityParkourModuleMsg.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ItemModuleMsg_pb2 as ItemModuleMsg__pb2
import ActivityModuleMsg_pb2 as ActivityModuleMsg__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ActivityParkourModuleMsg.proto',
  package='com.common.msg',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1e\x41\x63tivityParkourModuleMsg.proto\x12\x0e\x63om.common.msg\x1a\x13ItemModuleMsg.proto\x1a\x17\x41\x63tivityModuleMsg.proto\"(\n\x12ParkourInfoRequest\x12\x12\n\nactivityId\x18\x01 \x01(\t\"c\n\x13ParkourInfoResponse\x12\x0c\n\x04life\x18\x01 \x01(\x05\x12\x19\n\x11startRecoveryTime\x18\x02 \x01(\x03\x12\r\n\x05level\x18\x03 \x01(\x05\x12\x14\n\x0clastRewardId\x18\x04 \x01(\t\".\n\x18ParkourStartLevelRequest\x12\x12\n\nactivityId\x18\x01 \x01(\t\"D\n\x19ParkourStartLevelResponse\x12\x0c\n\x04life\x18\x01 \x01(\x05\x12\x19\n\x11startRecoveryTime\x18\x02 \x01(\x03\"W\n\x19ParkourFinishLevelRequest\x12\x12\n\nactivityId\x18\x01 \x01(\t\x12&\n\x05items\x18\x02 \x03(\x0b\x32\x17.com.common.msg.ItemMsg\"\x1c\n\x1aParkourFinishLevelResponse\"?\n\x15ParkourBuyLifeRequest\x12\x12\n\nactivityId\x18\x01 \x01(\t\x12\x12\n\nconsumeCnt\x18\x02 \x01(\x05\"\x18\n\x16ParkourBuyLifeResponse\".\n\x18ParkourRankRewardRequest\x12\x12\n\nactivityId\x18\x01 \x01(\t\"O\n\x19ParkourRankRewardResponse\x12\x32\n\x0brankRewards\x18\x01 \x03(\x0b\x32\x1d.com.common.msg.RankRewardMsg*\xaa\x02\n\"ActivityParkourModuleMsgSubCommand\x12.\n(ACTIVITYPARKOURMODULEMSG_SUB_PARKOURINFO\x10\xdd\xd3\x01\x12\x34\n.ACTIVITYPARKOURMODULEMSG_SUB_PARKOURSTARTLEVEL\x10\xde\xd3\x01\x12\x35\n/ACTIVITYPARKOURMODULEMSG_SUB_PARKOURFINISHLEVEL\x10\xdf\xd3\x01\x12\x31\n+ACTIVITYPARKOURMODULEMSG_SUB_PARKOURBUYLIFE\x10\xe0\xd3\x01\x12\x34\n.ACTIVITYPARKOURMODULEMSG_SUB_PARKOURRANKREWARD\x10\xe1\xd3\x01'
  ,
  dependencies=[ItemModuleMsg__pb2.DESCRIPTOR,ActivityModuleMsg__pb2.DESCRIPTOR,])

_ACTIVITYPARKOURMODULEMSGSUBCOMMAND = _descriptor.EnumDescriptor(
  name='ActivityParkourModuleMsgSubCommand',
  full_name='com.common.msg.ActivityParkourModuleMsgSubCommand',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACTIVITYPARKOURMODULEMSG_SUB_PARKOURINFO', index=0, number=27101,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ACTIVITYPARKOURMODULEMSG_SUB_PARKOURSTARTLEVEL', index=1, number=27102,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ACTIVITYPARKOURMODULEMSG_SUB_PARKOURFINISHLEVEL', index=2, number=27103,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ACTIVITYPARKOURMODULEMSG_SUB_PARKOURBUYLIFE', index=3, number=27104,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ACTIVITYPARKOURMODULEMSG_SUB_PARKOURRANKREWARD', index=4, number=27105,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=697,
  serialized_end=995,
)
_sym_db.RegisterEnumDescriptor(_ACTIVITYPARKOURMODULEMSGSUBCOMMAND)

ActivityParkourModuleMsgSubCommand = enum_type_wrapper.EnumTypeWrapper(_ACTIVITYPARKOURMODULEMSGSUBCOMMAND)
ACTIVITYPARKOURMODULEMSG_SUB_PARKOURINFO = 27101
ACTIVITYPARKOURMODULEMSG_SUB_PARKOURSTARTLEVEL = 27102
ACTIVITYPARKOURMODULEMSG_SUB_PARKOURFINISHLEVEL = 27103
ACTIVITYPARKOURMODULEMSG_SUB_PARKOURBUYLIFE = 27104
ACTIVITYPARKOURMODULEMSG_SUB_PARKOURRANKREWARD = 27105



_PARKOURINFOREQUEST = _descriptor.Descriptor(
  name='ParkourInfoRequest',
  full_name='com.common.msg.ParkourInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='activityId', full_name='com.common.msg.ParkourInfoRequest.activityId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=136,
)


_PARKOURINFORESPONSE = _descriptor.Descriptor(
  name='ParkourInfoResponse',
  full_name='com.common.msg.ParkourInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='life', full_name='com.common.msg.ParkourInfoResponse.life', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='startRecoveryTime', full_name='com.common.msg.ParkourInfoResponse.startRecoveryTime', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='level', full_name='com.common.msg.ParkourInfoResponse.level', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lastRewardId', full_name='com.common.msg.ParkourInfoResponse.lastRewardId', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=237,
)


_PARKOURSTARTLEVELREQUEST = _descriptor.Descriptor(
  name='ParkourStartLevelRequest',
  full_name='com.common.msg.ParkourStartLevelRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='activityId', full_name='com.common.msg.ParkourStartLevelRequest.activityId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=285,
)


_PARKOURSTARTLEVELRESPONSE = _descriptor.Descriptor(
  name='ParkourStartLevelResponse',
  full_name='com.common.msg.ParkourStartLevelResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='life', full_name='com.common.msg.ParkourStartLevelResponse.life', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='startRecoveryTime', full_name='com.common.msg.ParkourStartLevelResponse.startRecoveryTime', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=355,
)


_PARKOURFINISHLEVELREQUEST = _descriptor.Descriptor(
  name='ParkourFinishLevelRequest',
  full_name='com.common.msg.ParkourFinishLevelRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='activityId', full_name='com.common.msg.ParkourFinishLevelRequest.activityId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='items', full_name='com.common.msg.ParkourFinishLevelRequest.items', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=357,
  serialized_end=444,
)


_PARKOURFINISHLEVELRESPONSE = _descriptor.Descriptor(
  name='ParkourFinishLevelResponse',
  full_name='com.common.msg.ParkourFinishLevelResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=446,
  serialized_end=474,
)


_PARKOURBUYLIFEREQUEST = _descriptor.Descriptor(
  name='ParkourBuyLifeRequest',
  full_name='com.common.msg.ParkourBuyLifeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='activityId', full_name='com.common.msg.ParkourBuyLifeRequest.activityId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='consumeCnt', full_name='com.common.msg.ParkourBuyLifeRequest.consumeCnt', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=476,
  serialized_end=539,
)


_PARKOURBUYLIFERESPONSE = _descriptor.Descriptor(
  name='ParkourBuyLifeResponse',
  full_name='com.common.msg.ParkourBuyLifeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=541,
  serialized_end=565,
)


_PARKOURRANKREWARDREQUEST = _descriptor.Descriptor(
  name='ParkourRankRewardRequest',
  full_name='com.common.msg.ParkourRankRewardRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='activityId', full_name='com.common.msg.ParkourRankRewardRequest.activityId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=567,
  serialized_end=613,
)


_PARKOURRANKREWARDRESPONSE = _descriptor.Descriptor(
  name='ParkourRankRewardResponse',
  full_name='com.common.msg.ParkourRankRewardResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rankRewards', full_name='com.common.msg.ParkourRankRewardResponse.rankRewards', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=615,
  serialized_end=694,
)

_PARKOURFINISHLEVELREQUEST.fields_by_name['items'].message_type = ItemModuleMsg__pb2._ITEMMSG
_PARKOURRANKREWARDRESPONSE.fields_by_name['rankRewards'].message_type = ActivityModuleMsg__pb2._RANKREWARDMSG
DESCRIPTOR.message_types_by_name['ParkourInfoRequest'] = _PARKOURINFOREQUEST
DESCRIPTOR.message_types_by_name['ParkourInfoResponse'] = _PARKOURINFORESPONSE
DESCRIPTOR.message_types_by_name['ParkourStartLevelRequest'] = _PARKOURSTARTLEVELREQUEST
DESCRIPTOR.message_types_by_name['ParkourStartLevelResponse'] = _PARKOURSTARTLEVELRESPONSE
DESCRIPTOR.message_types_by_name['ParkourFinishLevelRequest'] = _PARKOURFINISHLEVELREQUEST
DESCRIPTOR.message_types_by_name['ParkourFinishLevelResponse'] = _PARKOURFINISHLEVELRESPONSE
DESCRIPTOR.message_types_by_name['ParkourBuyLifeRequest'] = _PARKOURBUYLIFEREQUEST
DESCRIPTOR.message_types_by_name['ParkourBuyLifeResponse'] = _PARKOURBUYLIFERESPONSE
DESCRIPTOR.message_types_by_name['ParkourRankRewardRequest'] = _PARKOURRANKREWARDREQUEST
DESCRIPTOR.message_types_by_name['ParkourRankRewardResponse'] = _PARKOURRANKREWARDRESPONSE
DESCRIPTOR.enum_types_by_name['ActivityParkourModuleMsgSubCommand'] = _ACTIVITYPARKOURMODULEMSGSUBCOMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ParkourInfoRequest = _reflection.GeneratedProtocolMessageType('ParkourInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _PARKOURINFOREQUEST,
  '__module__' : 'ActivityParkourModuleMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.common.msg.ParkourInfoRequest)
  })
_sym_db.RegisterMessage(ParkourInfoRequest)

ParkourInfoResponse = _reflection.GeneratedProtocolMessageType('ParkourInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _PARKOURINFORESPONSE,
  '__module__' : 'ActivityParkourModuleMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.common.msg.ParkourInfoResponse)
  })
_sym_db.RegisterMessage(ParkourInfoResponse)

ParkourStartLevelRequest = _reflection.GeneratedProtocolMessageType('ParkourStartLevelRequest', (_message.Message,), {
  'DESCRIPTOR' : _PARKOURSTARTLEVELREQUEST,
  '__module__' : 'ActivityParkourModuleMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.common.msg.ParkourStartLevelRequest)
  })
_sym_db.RegisterMessage(ParkourStartLevelRequest)

ParkourStartLevelResponse = _reflection.GeneratedProtocolMessageType('ParkourStartLevelResponse', (_message.Message,), {
  'DESCRIPTOR' : _PARKOURSTARTLEVELRESPONSE,
  '__module__' : 'ActivityParkourModuleMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.common.msg.ParkourStartLevelResponse)
  })
_sym_db.RegisterMessage(ParkourStartLevelResponse)

ParkourFinishLevelRequest = _reflection.GeneratedProtocolMessageType('ParkourFinishLevelRequest', (_message.Message,), {
  'DESCRIPTOR' : _PARKOURFINISHLEVELREQUEST,
  '__module__' : 'ActivityParkourModuleMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.common.msg.ParkourFinishLevelRequest)
  })
_sym_db.RegisterMessage(ParkourFinishLevelRequest)

ParkourFinishLevelResponse = _reflection.GeneratedProtocolMessageType('ParkourFinishLevelResponse', (_message.Message,), {
  'DESCRIPTOR' : _PARKOURFINISHLEVELRESPONSE,
  '__module__' : 'ActivityParkourModuleMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.common.msg.ParkourFinishLevelResponse)
  })
_sym_db.RegisterMessage(ParkourFinishLevelResponse)

ParkourBuyLifeRequest = _reflection.GeneratedProtocolMessageType('ParkourBuyLifeRequest', (_message.Message,), {
  'DESCRIPTOR' : _PARKOURBUYLIFEREQUEST,
  '__module__' : 'ActivityParkourModuleMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.common.msg.ParkourBuyLifeRequest)
  })
_sym_db.RegisterMessage(ParkourBuyLifeRequest)

ParkourBuyLifeResponse = _reflection.GeneratedProtocolMessageType('ParkourBuyLifeResponse', (_message.Message,), {
  'DESCRIPTOR' : _PARKOURBUYLIFERESPONSE,
  '__module__' : 'ActivityParkourModuleMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.common.msg.ParkourBuyLifeResponse)
  })
_sym_db.RegisterMessage(ParkourBuyLifeResponse)

ParkourRankRewardRequest = _reflection.GeneratedProtocolMessageType('ParkourRankRewardRequest', (_message.Message,), {
  'DESCRIPTOR' : _PARKOURRANKREWARDREQUEST,
  '__module__' : 'ActivityParkourModuleMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.common.msg.ParkourRankRewardRequest)
  })
_sym_db.RegisterMessage(ParkourRankRewardRequest)

ParkourRankRewardResponse = _reflection.GeneratedProtocolMessageType('ParkourRankRewardResponse', (_message.Message,), {
  'DESCRIPTOR' : _PARKOURRANKREWARDRESPONSE,
  '__module__' : 'ActivityParkourModuleMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.common.msg.ParkourRankRewardResponse)
  })
_sym_db.RegisterMessage(ParkourRankRewardResponse)


# @@protoc_insertion_point(module_scope)
