# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AdsModuleMsg.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='AdsModuleMsg.proto',
  package='com.common.msg',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x41\x64sModuleMsg.proto\x12\x0e\x63om.common.msg\"G\n\x0b\x41\x64sViewInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0clastViewTime\x18\x02 \x01(\x03\x12\x16\n\x0etodayViewCount\x18\x03 \x01(\x05\"\x19\n\x17\x41\x64sIncentiveInfoRequest\"\\\n\x18\x41\x64sIncentiveInfoResponse\x12\x10\n\x08\x61\x64sGroup\x18\x01 \x01(\t\x12.\n\tviewInfos\x18\x02 \x03(\x0b\x32\x1b.com.common.msg.AdsViewInfo\"E\n\x19\x41\x64sIncentiveRewardRequest\x12\r\n\x05\x61\x64sId\x18\x01 \x01(\t\x12\x19\n\x11\x65nergyRewardIndex\x18\x02 \x01(\x05\"\x1c\n\x1a\x41\x64sIncentiveRewardResponse*j\n\x16\x41\x64sModuleMsgSubCommand\x12&\n!ADSMODULEMSG_SUB_ADSINCENTIVEINFO\x10\xc9\x65\x12(\n#ADSMODULEMSG_SUB_ADSINCENTIVEREWARD\x10\xca\x65'
)

_ADSMODULEMSGSUBCOMMAND = _descriptor.EnumDescriptor(
  name='AdsModuleMsgSubCommand',
  full_name='com.common.msg.AdsModuleMsgSubCommand',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ADSMODULEMSG_SUB_ADSINCENTIVEINFO', index=0, number=13001,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ADSMODULEMSG_SUB_ADSINCENTIVEREWARD', index=1, number=13002,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=333,
  serialized_end=439,
)
_sym_db.RegisterEnumDescriptor(_ADSMODULEMSGSUBCOMMAND)

AdsModuleMsgSubCommand = enum_type_wrapper.EnumTypeWrapper(_ADSMODULEMSGSUBCOMMAND)
ADSMODULEMSG_SUB_ADSINCENTIVEINFO = 13001
ADSMODULEMSG_SUB_ADSINCENTIVEREWARD = 13002



_ADSVIEWINFO = _descriptor.Descriptor(
  name='AdsViewInfo',
  full_name='com.common.msg.AdsViewInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='com.common.msg.AdsViewInfo.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lastViewTime', full_name='com.common.msg.AdsViewInfo.lastViewTime', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='todayViewCount', full_name='com.common.msg.AdsViewInfo.todayViewCount', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=109,
)


_ADSINCENTIVEINFOREQUEST = _descriptor.Descriptor(
  name='AdsIncentiveInfoRequest',
  full_name='com.common.msg.AdsIncentiveInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=136,
)


_ADSINCENTIVEINFORESPONSE = _descriptor.Descriptor(
  name='AdsIncentiveInfoResponse',
  full_name='com.common.msg.AdsIncentiveInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='adsGroup', full_name='com.common.msg.AdsIncentiveInfoResponse.adsGroup', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='viewInfos', full_name='com.common.msg.AdsIncentiveInfoResponse.viewInfos', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=230,
)


_ADSINCENTIVEREWARDREQUEST = _descriptor.Descriptor(
  name='AdsIncentiveRewardRequest',
  full_name='com.common.msg.AdsIncentiveRewardRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='adsId', full_name='com.common.msg.AdsIncentiveRewardRequest.adsId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='energyRewardIndex', full_name='com.common.msg.AdsIncentiveRewardRequest.energyRewardIndex', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=301,
)


_ADSINCENTIVEREWARDRESPONSE = _descriptor.Descriptor(
  name='AdsIncentiveRewardResponse',
  full_name='com.common.msg.AdsIncentiveRewardResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=331,
)

_ADSINCENTIVEINFORESPONSE.fields_by_name['viewInfos'].message_type = _ADSVIEWINFO
DESCRIPTOR.message_types_by_name['AdsViewInfo'] = _ADSVIEWINFO
DESCRIPTOR.message_types_by_name['AdsIncentiveInfoRequest'] = _ADSINCENTIVEINFOREQUEST
DESCRIPTOR.message_types_by_name['AdsIncentiveInfoResponse'] = _ADSINCENTIVEINFORESPONSE
DESCRIPTOR.message_types_by_name['AdsIncentiveRewardRequest'] = _ADSINCENTIVEREWARDREQUEST
DESCRIPTOR.message_types_by_name['AdsIncentiveRewardResponse'] = _ADSINCENTIVEREWARDRESPONSE
DESCRIPTOR.enum_types_by_name['AdsModuleMsgSubCommand'] = _ADSMODULEMSGSUBCOMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AdsViewInfo = _reflection.GeneratedProtocolMessageType('AdsViewInfo', (_message.Message,), {
  'DESCRIPTOR' : _ADSVIEWINFO,
  '__module__' : 'AdsModuleMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.common.msg.AdsViewInfo)
  })
_sym_db.RegisterMessage(AdsViewInfo)

AdsIncentiveInfoRequest = _reflection.GeneratedProtocolMessageType('AdsIncentiveInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADSINCENTIVEINFOREQUEST,
  '__module__' : 'AdsModuleMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.common.msg.AdsIncentiveInfoRequest)
  })
_sym_db.RegisterMessage(AdsIncentiveInfoRequest)

AdsIncentiveInfoResponse = _reflection.GeneratedProtocolMessageType('AdsIncentiveInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADSINCENTIVEINFORESPONSE,
  '__module__' : 'AdsModuleMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.common.msg.AdsIncentiveInfoResponse)
  })
_sym_db.RegisterMessage(AdsIncentiveInfoResponse)

AdsIncentiveRewardRequest = _reflection.GeneratedProtocolMessageType('AdsIncentiveRewardRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADSINCENTIVEREWARDREQUEST,
  '__module__' : 'AdsModuleMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.common.msg.AdsIncentiveRewardRequest)
  })
_sym_db.RegisterMessage(AdsIncentiveRewardRequest)

AdsIncentiveRewardResponse = _reflection.GeneratedProtocolMessageType('AdsIncentiveRewardResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADSINCENTIVEREWARDRESPONSE,
  '__module__' : 'AdsModuleMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.common.msg.AdsIncentiveRewardResponse)
  })
_sym_db.RegisterMessage(AdsIncentiveRewardResponse)


# @@protoc_insertion_point(module_scope)
