# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DotTaskModuleMsg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CommonTaskModuleMsg_pb2 as CommonTaskModuleMsg__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x44otTaskModuleMsg.proto\x12\x0e\x63om.common.msg\x1a\x19\x43ommonTaskModuleMsg.proto\"\x14\n\x12\x44otTaskInfoRequest\"@\n\x13\x44otTaskInfoResponse\x12)\n\x05tasks\x18\x01 \x03(\x0b\x32\x1a.com.common.msg.CommonTask\"&\n\x14SubmitDotTaskRequest\x12\x0e\n\x06taskId\x18\x01 \x01(\t\"\x17\n\x15SubmitDotTaskResponse*n\n\x1a\x44otTaskModuleMsgSubCommand\x12&\n DOTTASKMODULEMSG_SUB_DOTTASKINFO\x10\xfd\xe8\x01\x12(\n\"DOTTASKMODULEMSG_SUB_SUBMITDOTTASK\x10\xfe\xe8\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DotTaskModuleMsg_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_DOTTASKMODULEMSGSUBCOMMAND']._serialized_start=222
  _globals['_DOTTASKMODULEMSGSUBCOMMAND']._serialized_end=332
  _globals['_DOTTASKINFOREQUEST']._serialized_start=69
  _globals['_DOTTASKINFOREQUEST']._serialized_end=89
  _globals['_DOTTASKINFORESPONSE']._serialized_start=91
  _globals['_DOTTASKINFORESPONSE']._serialized_end=155
  _globals['_SUBMITDOTTASKREQUEST']._serialized_start=157
  _globals['_SUBMITDOTTASKREQUEST']._serialized_end=195
  _globals['_SUBMITDOTTASKRESPONSE']._serialized_start=197
  _globals['_SUBMITDOTTASKRESPONSE']._serialized_end=220
# @@protoc_insertion_point(module_scope)
