# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DragonBuildingModuleMsg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ItemModuleMsg_pb2 as ItemModuleMsg__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x44ragonBuildingModuleMsg.proto\x12\x0e\x63om.common.msg\x1a\x13ItemModuleMsg.proto\"`\n\x15\x44ragonBuildingTaskMsg\x12\x0e\n\x06taskId\x18\x01 \x02(\t\x12\x0f\n\x07taskCnt\x18\x02 \x02(\x05\x12\r\n\x05state\x18\x03 \x02(\x05\x12\x17\n\x0ftaskBuildingCnt\x18\x04 \x02(\x05\"T\n\x11\x44ragonBuildingMsg\x12\n\n\x02id\x18\x01 \x02(\t\x12\x0b\n\x03tid\x18\x02 \x02(\t\x12\x0b\n\x03pos\x18\x03 \x03(\x05\x12\x19\n\x11rewardRefreshTime\x18\x04 \x02(\x03\"?\n\x18\x44ragonBuildingSetRequest\x12\x16\n\x0eitemTemplateId\x18\x01 \x02(\t\x12\x0b\n\x03pos\x18\x02 \x03(\x05\"\'\n\x19\x44ragonBuildingSetResponse\x12\n\n\x02id\x18\x01 \x02(\t\"4\n\x19\x44ragonBuildingMoveRequest\x12\n\n\x02id\x18\x01 \x02(\t\x12\x0b\n\x03pos\x18\x02 \x03(\x05\"\x1c\n\x1a\x44ragonBuildingMoveResponse\"/\n!DragonBuildingHangUpRewardRequest\x12\n\n\x02id\x18\x01 \x03(\t\"$\n\"DragonBuildingHangUpRewardResponse\"1\n\x1f\x44ragonBuildingTaskRewardRequest\x12\x0e\n\x06taskId\x18\x01 \x02(\t\"\"\n DragonBuildingTaskRewardResponse\"\"\n DragonBuildingTaskRefreshRequest\"X\n!DragonBuildingTaskRefreshResponse\x12\x33\n\x04task\x18\x01 \x01(\x0b\x32%.com.common.msg.DragonBuildingTaskMsg*\xc5\x02\n!DragonBuildingModuleMsgSubCommand\x12\x33\n-DRAGONBUILDINGMODULEMSG_SUB_DRAGONBUILDINGSET\x10\x91\xe4\x01\x12\x34\n.DRAGONBUILDINGMODULEMSG_SUB_DRAGONBUILDINGMOVE\x10\x92\xe4\x01\x12<\n6DRAGONBUILDINGMODULEMSG_SUB_DRAGONBUILDINGHANGUPREWARD\x10\x93\xe4\x01\x12:\n4DRAGONBUILDINGMODULEMSG_SUB_DRAGONBUILDINGTASKREWARD\x10\x94\xe4\x01\x12;\n5DRAGONBUILDINGMODULEMSG_SUB_DRAGONBUILDINGTASKREFRESH\x10\x95\xe4\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DragonBuildingModuleMsg_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_DRAGONBUILDINGMODULEMSGSUBCOMMAND']._serialized_start=745
  _globals['_DRAGONBUILDINGMODULEMSGSUBCOMMAND']._serialized_end=1070
  _globals['_DRAGONBUILDINGTASKMSG']._serialized_start=70
  _globals['_DRAGONBUILDINGTASKMSG']._serialized_end=166
  _globals['_DRAGONBUILDINGMSG']._serialized_start=168
  _globals['_DRAGONBUILDINGMSG']._serialized_end=252
  _globals['_DRAGONBUILDINGSETREQUEST']._serialized_start=254
  _globals['_DRAGONBUILDINGSETREQUEST']._serialized_end=317
  _globals['_DRAGONBUILDINGSETRESPONSE']._serialized_start=319
  _globals['_DRAGONBUILDINGSETRESPONSE']._serialized_end=358
  _globals['_DRAGONBUILDINGMOVEREQUEST']._serialized_start=360
  _globals['_DRAGONBUILDINGMOVEREQUEST']._serialized_end=412
  _globals['_DRAGONBUILDINGMOVERESPONSE']._serialized_start=414
  _globals['_DRAGONBUILDINGMOVERESPONSE']._serialized_end=442
  _globals['_DRAGONBUILDINGHANGUPREWARDREQUEST']._serialized_start=444
  _globals['_DRAGONBUILDINGHANGUPREWARDREQUEST']._serialized_end=491
  _globals['_DRAGONBUILDINGHANGUPREWARDRESPONSE']._serialized_start=493
  _globals['_DRAGONBUILDINGHANGUPREWARDRESPONSE']._serialized_end=529
  _globals['_DRAGONBUILDINGTASKREWARDREQUEST']._serialized_start=531
  _globals['_DRAGONBUILDINGTASKREWARDREQUEST']._serialized_end=580
  _globals['_DRAGONBUILDINGTASKREWARDRESPONSE']._serialized_start=582
  _globals['_DRAGONBUILDINGTASKREWARDRESPONSE']._serialized_end=616
  _globals['_DRAGONBUILDINGTASKREFRESHREQUEST']._serialized_start=618
  _globals['_DRAGONBUILDINGTASKREFRESHREQUEST']._serialized_end=652
  _globals['_DRAGONBUILDINGTASKREFRESHRESPONSE']._serialized_start=654
  _globals['_DRAGONBUILDINGTASKREFRESHRESPONSE']._serialized_end=742
# @@protoc_insertion_point(module_scope)
