# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SkinProduceModuleMsg.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ItemModuleMsg_pb2 as ItemModuleMsg__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='SkinProduceModuleMsg.proto',
  package='com.common.msg',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1aSkinProduceModuleMsg.proto\x12\x0e\x63om.common.msg\x1a\x13ItemModuleMsg.proto\"=\n\x0eSkinProduceMsg\x12\r\n\x05tplId\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x12\r\n\x05state\x18\x03 \x01(\x05\"\x14\n\x12ProduceInfoRequest\"G\n\x13ProduceInfoResponse\x12\x30\n\x08produces\x18\x01 \x03(\x0b\x32\x1e.com.common.msg.SkinProduceMsg\"\x1e\n\rUnlockRequest\x12\r\n\x05tplId\x18\x01 \x01(\t\"\x10\n\x0eUnlockResponse\")\n\x18ProduceDragonSkinRequest\x12\r\n\x05tplId\x18\x01 \x01(\t\"\xca\x01\n\x19ProduceDragonSkinResponse\x12\x0c\n\x04succ\x18\x01 \x01(\x08\x12.\n\x07newSkin\x18\x02 \x01(\x0b\x32\x1d.com.common.msg.DragonSkinMsg\x12&\n\x05items\x18\x03 \x03(\x0b\x32\x17.com.common.msg.ItemMsg\x12/\n\x07produce\x18\x04 \x01(\x0b\x32\x1e.com.common.msg.SkinProduceMsg\x12\x16\n\x0e\x63onsumeSkinIds\x18\x05 \x03(\x03\"/\n\x14UseDesignItemRequest\x12\x17\n\x0fitemTemplateIds\x18\x01 \x03(\t\"\x17\n\x15UseDesignItemResponse\"B\n\x18UseDragonSkinItemRequest\x12&\n\x05items\x18\x01 \x03(\x0b\x32\x17.com.common.msg.ItemMsg\"I\n\x19UseDragonSkinItemResponse\x12,\n\x05skins\x18\x01 \x03(\x0b\x32\x1d.com.common.msg.DragonSkinMsg\")\n\x17\x44\x65leteDragonSkinRequest\x12\x0e\n\x06skinId\x18\x01 \x01(\x03\"P\n\x18\x44\x65leteDragonSkinResponse\x12\x34\n\x08\x63reature\x18\x01 \x01(\x0b\x32\".com.common.msg.MagicalCreatureMsg\"\x18\n\x16OpenSkinProduceRequest\"\x19\n\x17OpenSkinProduceResponse*\xe6\x02\n\x1eSkinProduceModuleMsgSubCommand\x12*\n$SKINPRODUCEMODULEMSG_SUB_PRODUCEINFO\x10\xcd\xd0\x01\x12%\n\x1fSKINPRODUCEMODULEMSG_SUB_UNLOCK\x10\xce\xd0\x01\x12\x30\n*SKINPRODUCEMODULEMSG_SUB_PRODUCEDRAGONSKIN\x10\xcf\xd0\x01\x12,\n&SKINPRODUCEMODULEMSG_SUB_USEDESIGNITEM\x10\xd0\xd0\x01\x12\x30\n*SKINPRODUCEMODULEMSG_SUB_USEDRAGONSKINITEM\x10\xd1\xd0\x01\x12/\n)SKINPRODUCEMODULEMSG_SUB_DELETEDRAGONSKIN\x10\xd2\xd0\x01\x12.\n(SKINPRODUCEMODULEMSG_SUB_OPENSKINPRODUCE\x10\xd3\xd0\x01'
  ,
  dependencies=[ItemModuleMsg__pb2.DESCRIPTOR,])

_SKINPRODUCEMODULEMSGSUBCOMMAND = _descriptor.EnumDescriptor(
  name='SkinProduceModuleMsgSubCommand',
  full_name='com.common.msg.SkinProduceModuleMsgSubCommand',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SKINPRODUCEMODULEMSG_SUB_PRODUCEINFO', index=0, number=26701,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SKINPRODUCEMODULEMSG_SUB_UNLOCK', index=1, number=26702,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SKINPRODUCEMODULEMSG_SUB_PRODUCEDRAGONSKIN', index=2, number=26703,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SKINPRODUCEMODULEMSG_SUB_USEDESIGNITEM', index=3, number=26704,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SKINPRODUCEMODULEMSG_SUB_USEDRAGONSKINITEM', index=4, number=26705,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SKINPRODUCEMODULEMSG_SUB_DELETEDRAGONSKIN', index=5, number=26706,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SKINPRODUCEMODULEMSG_SUB_OPENSKINPRODUCE', index=6, number=26707,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=919,
  serialized_end=1277,
)
_sym_db.RegisterEnumDescriptor(_SKINPRODUCEMODULEMSGSUBCOMMAND)

SkinProduceModuleMsgSubCommand = enum_type_wrapper.EnumTypeWrapper(_SKINPRODUCEMODULEMSGSUBCOMMAND)
SKINPRODUCEMODULEMSG_SUB_PRODUCEINFO = 26701
SKINPRODUCEMODULEMSG_SUB_UNLOCK = 26702
SKINPRODUCEMODULEMSG_SUB_PRODUCEDRAGONSKIN = 26703
SKINPRODUCEMODULEMSG_SUB_USEDESIGNITEM = 26704
SKINPRODUCEMODULEMSG_SUB_USEDRAGONSKINITEM = 26705
SKINPRODUCEMODULEMSG_SUB_DELETEDRAGONSKIN = 26706
SKINPRODUCEMODULEMSG_SUB_OPENSKINPRODUCE = 26707



_SKINPRODUCEMSG = _descriptor.Descriptor(
  name='SkinProduceMsg',
  full_name='com.common.msg.SkinProduceMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tplId', full_name='com.common.msg.SkinProduceMsg.tplId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count', full_name='com.common.msg.SkinProduceMsg.count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='com.common.msg.SkinProduceMsg.state', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=128,
)


_PRODUCEINFOREQUEST = _descriptor.Descriptor(
  name='ProduceInfoRequest',
  full_name='com.common.msg.ProduceInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=150,
)


_PRODUCEINFORESPONSE = _descriptor.Descriptor(
  name='ProduceInfoResponse',
  full_name='com.common.msg.ProduceInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='produces', full_name='com.common.msg.ProduceInfoResponse.produces', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=223,
)


_UNLOCKREQUEST = _descriptor.Descriptor(
  name='UnlockRequest',
  full_name='com.common.msg.UnlockRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tplId', full_name='com.common.msg.UnlockRequest.tplId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=255,
)


_UNLOCKRESPONSE = _descriptor.Descriptor(
  name='UnlockResponse',
  full_name='com.common.msg.UnlockResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=273,
)


_PRODUCEDRAGONSKINREQUEST = _descriptor.Descriptor(
  name='ProduceDragonSkinRequest',
  full_name='com.common.msg.ProduceDragonSkinRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tplId', full_name='com.common.msg.ProduceDragonSkinRequest.tplId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=275,
  serialized_end=316,
)


_PRODUCEDRAGONSKINRESPONSE = _descriptor.Descriptor(
  name='ProduceDragonSkinResponse',
  full_name='com.common.msg.ProduceDragonSkinResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='succ', full_name='com.common.msg.ProduceDragonSkinResponse.succ', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='newSkin', full_name='com.common.msg.ProduceDragonSkinResponse.newSkin', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='items', full_name='com.common.msg.ProduceDragonSkinResponse.items', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='produce', full_name='com.common.msg.ProduceDragonSkinResponse.produce', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='consumeSkinIds', full_name='com.common.msg.ProduceDragonSkinResponse.consumeSkinIds', index=4,
      number=5, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=319,
  serialized_end=521,
)


_USEDESIGNITEMREQUEST = _descriptor.Descriptor(
  name='UseDesignItemRequest',
  full_name='com.common.msg.UseDesignItemRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='itemTemplateIds', full_name='com.common.msg.UseDesignItemRequest.itemTemplateIds', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=523,
  serialized_end=570,
)


_USEDESIGNITEMRESPONSE = _descriptor.Descriptor(
  name='UseDesignItemResponse',
  full_name='com.common.msg.UseDesignItemResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=572,
  serialized_end=595,
)


_USEDRAGONSKINITEMREQUEST = _descriptor.Descriptor(
  name='UseDragonSkinItemRequest',
  full_name='com.common.msg.UseDragonSkinItemRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='com.common.msg.UseDragonSkinItemRequest.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=597,
  serialized_end=663,
)


_USEDRAGONSKINITEMRESPONSE = _descriptor.Descriptor(
  name='UseDragonSkinItemResponse',
  full_name='com.common.msg.UseDragonSkinItemResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='skins', full_name='com.common.msg.UseDragonSkinItemResponse.skins', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=665,
  serialized_end=738,
)


_DELETEDRAGONSKINREQUEST = _descriptor.Descriptor(
  name='DeleteDragonSkinRequest',
  full_name='com.common.msg.DeleteDragonSkinRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='skinId', full_name='com.common.msg.DeleteDragonSkinRequest.skinId', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=740,
  serialized_end=781,
)


_DELETEDRAGONSKINRESPONSE = _descriptor.Descriptor(
  name='DeleteDragonSkinResponse',
  full_name='com.common.msg.DeleteDragonSkinResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='creature', full_name='com.common.msg.DeleteDragonSkinResponse.creature', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=783,
  serialized_end=863,
)


_OPENSKINPRODUCEREQUEST = _descriptor.Descriptor(
  name='OpenSkinProduceRequest',
  full_name='com.common.msg.OpenSkinProduceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=865,
  serialized_end=889,
)


_OPENSKINPRODUCERESPONSE = _descriptor.Descriptor(
  name='OpenSkinProduceResponse',
  full_name='com.common.msg.OpenSkinProduceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=891,
  serialized_end=916,
)

_PRODUCEINFORESPONSE.fields_by_name['produces'].message_type = _SKINPRODUCEMSG
_PRODUCEDRAGONSKINRESPONSE.fields_by_name['newSkin'].message_type = ItemModuleMsg__pb2._DRAGONSKINMSG
_PRODUCEDRAGONSKINRESPONSE.fields_by_name['items'].message_type = ItemModuleMsg__pb2._ITEMMSG
_PRODUCEDRAGONSKINRESPONSE.fields_by_name['produce'].message_type = _SKINPRODUCEMSG
_USEDRAGONSKINITEMREQUEST.fields_by_name['items'].message_type = ItemModuleMsg__pb2._ITEMMSG
_USEDRAGONSKINITEMRESPONSE.fields_by_name['skins'].message_type = ItemModuleMsg__pb2._DRAGONSKINMSG
_DELETEDRAGONSKINRESPONSE.fields_by_name['creature'].message_type = ItemModuleMsg__pb2._MAGICALCREATUREMSG
DESCRIPTOR.message_types_by_name['SkinProduceMsg'] = _SKINPRODUCEMSG
DESCRIPTOR.message_types_by_name['ProduceInfoRequest'] = _PRODUCEINFOREQUEST
DESCRIPTOR.message_types_by_name['ProduceInfoResponse'] = _PRODUCEINFORESPONSE
DESCRIPTOR.message_types_by_name['UnlockRequest'] = _UNLOCKREQUEST
DESCRIPTOR.message_types_by_name['UnlockResponse'] = _UNLOCKRESPONSE
DESCRIPTOR.message_types_by_name['ProduceDragonSkinRequest'] = _PRODUCEDRAGONSKINREQUEST
DESCRIPTOR.message_types_by_name['ProduceDragonSkinResponse'] = _PRODUCEDRAGONSKINRESPONSE
DESCRIPTOR.message_types_by_name['UseDesignItemRequest'] = _USEDESIGNITEMREQUEST
DESCRIPTOR.message_types_by_name['UseDesignItemResponse'] = _USEDESIGNITEMRESPONSE
DESCRIPTOR.message_types_by_name['UseDragonSkinItemRequest'] = _USEDRAGONSKINITEMREQUEST
DESCRIPTOR.message_types_by_name['UseDragonSkinItemResponse'] = _USEDRAGONSKINITEMRESPONSE
DESCRIPTOR.message_types_by_name['DeleteDragonSkinRequest'] = _DELETEDRAGONSKINREQUEST
DESCRIPTOR.message_types_by_name['DeleteDragonSkinResponse'] = _DELETEDRAGONSKINRESPONSE
DESCRIPTOR.message_types_by_name['OpenSkinProduceRequest'] = _OPENSKINPRODUCEREQUEST
DESCRIPTOR.message_types_by_name['OpenSkinProduceResponse'] = _OPENSKINPRODUCERESPONSE
DESCRIPTOR.enum_types_by_name['SkinProduceModuleMsgSubCommand'] = _SKINPRODUCEMODULEMSGSUBCOMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SkinProduceMsg = _reflection.GeneratedProtocolMessageType('SkinProduceMsg', (_message.Message,), {
  'DESCRIPTOR' : _SKINPRODUCEMSG,
  '__module__' : 'SkinProduceModuleMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.common.msg.SkinProduceMsg)
  })
_sym_db.RegisterMessage(SkinProduceMsg)

ProduceInfoRequest = _reflection.GeneratedProtocolMessageType('ProduceInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCEINFOREQUEST,
  '__module__' : 'SkinProduceModuleMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.common.msg.ProduceInfoRequest)
  })
_sym_db.RegisterMessage(ProduceInfoRequest)

ProduceInfoResponse = _reflection.GeneratedProtocolMessageType('ProduceInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCEINFORESPONSE,
  '__module__' : 'SkinProduceModuleMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.common.msg.ProduceInfoResponse)
  })
_sym_db.RegisterMessage(ProduceInfoResponse)

UnlockRequest = _reflection.GeneratedProtocolMessageType('UnlockRequest', (_message.Message,), {
  'DESCRIPTOR' : _UNLOCKREQUEST,
  '__module__' : 'SkinProduceModuleMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.common.msg.UnlockRequest)
  })
_sym_db.RegisterMessage(UnlockRequest)

UnlockResponse = _reflection.GeneratedProtocolMessageType('UnlockResponse', (_message.Message,), {
  'DESCRIPTOR' : _UNLOCKRESPONSE,
  '__module__' : 'SkinProduceModuleMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.common.msg.UnlockResponse)
  })
_sym_db.RegisterMessage(UnlockResponse)

ProduceDragonSkinRequest = _reflection.GeneratedProtocolMessageType('ProduceDragonSkinRequest', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCEDRAGONSKINREQUEST,
  '__module__' : 'SkinProduceModuleMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.common.msg.ProduceDragonSkinRequest)
  })
_sym_db.RegisterMessage(ProduceDragonSkinRequest)

ProduceDragonSkinResponse = _reflection.GeneratedProtocolMessageType('ProduceDragonSkinResponse', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCEDRAGONSKINRESPONSE,
  '__module__' : 'SkinProduceModuleMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.common.msg.ProduceDragonSkinResponse)
  })
_sym_db.RegisterMessage(ProduceDragonSkinResponse)

UseDesignItemRequest = _reflection.GeneratedProtocolMessageType('UseDesignItemRequest', (_message.Message,), {
  'DESCRIPTOR' : _USEDESIGNITEMREQUEST,
  '__module__' : 'SkinProduceModuleMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.common.msg.UseDesignItemRequest)
  })
_sym_db.RegisterMessage(UseDesignItemRequest)

UseDesignItemResponse = _reflection.GeneratedProtocolMessageType('UseDesignItemResponse', (_message.Message,), {
  'DESCRIPTOR' : _USEDESIGNITEMRESPONSE,
  '__module__' : 'SkinProduceModuleMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.common.msg.UseDesignItemResponse)
  })
_sym_db.RegisterMessage(UseDesignItemResponse)

UseDragonSkinItemRequest = _reflection.GeneratedProtocolMessageType('UseDragonSkinItemRequest', (_message.Message,), {
  'DESCRIPTOR' : _USEDRAGONSKINITEMREQUEST,
  '__module__' : 'SkinProduceModuleMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.common.msg.UseDragonSkinItemRequest)
  })
_sym_db.RegisterMessage(UseDragonSkinItemRequest)

UseDragonSkinItemResponse = _reflection.GeneratedProtocolMessageType('UseDragonSkinItemResponse', (_message.Message,), {
  'DESCRIPTOR' : _USEDRAGONSKINITEMRESPONSE,
  '__module__' : 'SkinProduceModuleMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.common.msg.UseDragonSkinItemResponse)
  })
_sym_db.RegisterMessage(UseDragonSkinItemResponse)

DeleteDragonSkinRequest = _reflection.GeneratedProtocolMessageType('DeleteDragonSkinRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEDRAGONSKINREQUEST,
  '__module__' : 'SkinProduceModuleMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.common.msg.DeleteDragonSkinRequest)
  })
_sym_db.RegisterMessage(DeleteDragonSkinRequest)

DeleteDragonSkinResponse = _reflection.GeneratedProtocolMessageType('DeleteDragonSkinResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETEDRAGONSKINRESPONSE,
  '__module__' : 'SkinProduceModuleMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.common.msg.DeleteDragonSkinResponse)
  })
_sym_db.RegisterMessage(DeleteDragonSkinResponse)

OpenSkinProduceRequest = _reflection.GeneratedProtocolMessageType('OpenSkinProduceRequest', (_message.Message,), {
  'DESCRIPTOR' : _OPENSKINPRODUCEREQUEST,
  '__module__' : 'SkinProduceModuleMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.common.msg.OpenSkinProduceRequest)
  })
_sym_db.RegisterMessage(OpenSkinProduceRequest)

OpenSkinProduceResponse = _reflection.GeneratedProtocolMessageType('OpenSkinProduceResponse', (_message.Message,), {
  'DESCRIPTOR' : _OPENSKINPRODUCERESPONSE,
  '__module__' : 'SkinProduceModuleMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.common.msg.OpenSkinProduceResponse)
  })
_sym_db.RegisterMessage(OpenSkinProduceResponse)


# @@protoc_insertion_point(module_scope)
