# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TaskModuleMsg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13TaskModuleMsg.proto\x12\x0e\x63om.common.msg\"\x11\n\x0fTaskListRequest\"+\n\nProtoTypes\x12\x0e\n\x06typeId\x18\x01 \x02(\x05\x12\r\n\x05\x64\x61tas\x18\x02 \x02(\x0c\"O\n\x10TaskConditionMsg\x12\x0f\n\x07indexId\x18\x01 \x02(\x05\x12*\n\x06params\x18\x02 \x03(\x0b\x32\x1a.com.common.msg.ProtoTypes\"^\n\x07TaskMsg\x12\x0e\n\x06taskId\x18\x01 \x02(\t\x12\r\n\x05state\x18\x02 \x02(\x05\x12\x34\n\nconditions\x18\x03 \x03(\x0b\x32 .com.common.msg.TaskConditionMsg\"V\n\x0cTaskGraphMsg\x12\x0f\n\x07graphId\x18\x01 \x02(\t\x12\r\n\x05state\x18\x02 \x02(\x05\x12&\n\x05tasks\x18\x03 \x03(\x0b\x32\x17.com.common.msg.TaskMsg\"@\n\x10TaskListResponse\x12,\n\x06graphs\x18\x01 \x03(\x0b\x32\x1c.com.common.msg.TaskGraphMsg\"4\n\x11SubmitTaskRequest\x12\x0e\n\x06taskId\x18\x01 \x02(\t\x12\x0f\n\x07graphId\x18\x02 \x02(\t\"\x14\n\x12SubmitTaskResponse\"a\n\x1a\x46inishTaskConditionRequest\x12\x0f\n\x07graphId\x18\x01 \x02(\t\x12\x0e\n\x06taskId\x18\x02 \x02(\t\x12\x10\n\x08\x63onIndex\x18\x03 \x02(\x05\x12\x10\n\x08\x64iamonds\x18\x04 \x02(\x05\"\x1d\n\x1b\x46inishTaskConditionResponse\"6\n\x13GMSubmitTaskRequest\x12\x0f\n\x07graphId\x18\x01 \x02(\t\x12\x0e\n\x06taskId\x18\x02 \x02(\t\"\x16\n\x14GMSubmitTaskResponse*\xae\x01\n\x17TaskModuleMsgSubCommand\x12!\n\x1cTASKMODULEMSG_SUB_SUBMITTASK\x10\x91N\x12\x1f\n\x1aTASKMODULEMSG_SUB_TASKLIST\x10\x92N\x12*\n%TASKMODULEMSG_SUB_FINISHTASKCONDITION\x10\x93N\x12#\n\x1eTASKMODULEMSG_SUB_GMSUBMITTASK\x10\x94N*<\n\rProtoTypeEnum\x12\x14\n\x10PROTO_TYPE_INT32\x10\x00\x12\x15\n\x11PROTO_TYPE_STRING\x10\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TaskModuleMsg_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_TASKMODULEMSGSUBCOMMAND']._serialized_start=721
  _globals['_TASKMODULEMSGSUBCOMMAND']._serialized_end=895
  _globals['_PROTOTYPEENUM']._serialized_start=897
  _globals['_PROTOTYPEENUM']._serialized_end=957
  _globals['_TASKLISTREQUEST']._serialized_start=39
  _globals['_TASKLISTREQUEST']._serialized_end=56
  _globals['_PROTOTYPES']._serialized_start=58
  _globals['_PROTOTYPES']._serialized_end=101
  _globals['_TASKCONDITIONMSG']._serialized_start=103
  _globals['_TASKCONDITIONMSG']._serialized_end=182
  _globals['_TASKMSG']._serialized_start=184
  _globals['_TASKMSG']._serialized_end=278
  _globals['_TASKGRAPHMSG']._serialized_start=280
  _globals['_TASKGRAPHMSG']._serialized_end=366
  _globals['_TASKLISTRESPONSE']._serialized_start=368
  _globals['_TASKLISTRESPONSE']._serialized_end=432
  _globals['_SUBMITTASKREQUEST']._serialized_start=434
  _globals['_SUBMITTASKREQUEST']._serialized_end=486
  _globals['_SUBMITTASKRESPONSE']._serialized_start=488
  _globals['_SUBMITTASKRESPONSE']._serialized_end=508
  _globals['_FINISHTASKCONDITIONREQUEST']._serialized_start=510
  _globals['_FINISHTASKCONDITIONREQUEST']._serialized_end=607
  _globals['_FINISHTASKCONDITIONRESPONSE']._serialized_start=609
  _globals['_FINISHTASKCONDITIONRESPONSE']._serialized_end=638
  _globals['_GMSUBMITTASKREQUEST']._serialized_start=640
  _globals['_GMSUBMITTASKREQUEST']._serialized_end=694
  _globals['_GMSUBMITTASKRESPONSE']._serialized_start=696
  _globals['_GMSUBMITTASKRESPONSE']._serialized_end=718
# @@protoc_insertion_point(module_scope)
